### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by axic** [axic/keccakjs#5]
Would be nice having tests and having them part of prepublish. Tests should be run against both `kecckajs` and `keccakjs/browser`.

**Comment by axic** [comment]
@fanatid would you be interested adding tests?

**Comment by fanatid** [comment]
yep, I'd like add tests, we can start from https://github.com/crypto-browserify/hash-test-vectors/issues/3

**Comment by axic** [comment]
Added in 611d16ba5a10c1f42f6f1d50a6efed095275d96e
