### ISSUE TITLE
Update to sha3@2.0.1 so keccakjs will work again on Node 12

### ISSUE THREAD

**Issue by davidmurdoch** [axic/keccakjs#8]

**Comment by adrianmcli** [comment]
@axic Can we merge one of the 2 PRs that solve this issue? More specifically, #9 and #12. This is breaking our CI on Node 12 which has now become the latest supported Node version.

<img width="341" alt="Screen Shot 2019-04-26 at 5 37 41 PM" src="https://user-images.githubusercontent.com/943555/56795208-e7f56b00-684a-11e9-947e-50d4aecc2964.png">

**Comment by davidmurdoch** [comment]
Closing as node-sha3@1.2.3 was released which added support for Node 12.
